### ISSUE TITLE
Avaliacao A5

### ISSUE THREAD

**Issue by ArimaBatista** [filipe-franco-f/projeto_MC426_2023#58]
Testes automatizados

**Comment by ArimaBatista** [comment]
- Teste Grafo de Causa-Efeito na classe de comunidade
     Testando em diferentes cenarios o resultado de tentar adcionar algum a sua comunidade sendo se ela ja foi adcionada por outro user ou se ela ja pertence ou se ela não esta presente na sua comunidade 
![test_comunidadecausaefeito](https://github.com/filipe-franco-f/projeto_MC426_2023/assets/80778627/8aab81ca-7208-4673-a7de-a3922c48b1c6)

- Teste Valor limite na adição de dívidas na parte de finanças
     Testando diferentes cenarios em relação aos valores das dívidas adicionadas. Elas devem ser valores com duas casas decimais >= 0.01 ou <= -0.01
![test_divida_valor_limite](https://github.com/filipe-franco-f/projeto_MC426_2023/assets/102170519/9d5d4f0b-4366-4154-9e41-c6593b767912)

- Teste Valor limite no agendamento de reuniões
     Testando diferentes cenarios em relação as datas e horários das reuniões adicionadas. Elas não podem ser antes do dia e horário atual.
![test_reuniao_valor_limite](https://github.com/filipe-franco-f/projeto_MC426_2023/assets/102170519/0b3ba640-b4c6-4593-96f4-f398464ebd15)

**Comment by filipe-franco-f** [comment]
Os testes da avaliação A5 foram adicionados e realizados.
